config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new]
  end
  get "/users/:id/posts/:id/new" => "comments#new", as: 'new_user_post_comment'
  post "/users/:id/posts/:id" => "comments#create", as: 'user_post_comments'
  post "/users/:id/posts/:id/likes" => "likes#create", as: 'user_post_likes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:commentscounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likescounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: 'User'
  after_save :update_post_counter
  validates :title, presence: true, length: { maximum: 250 }

  validates :commentscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likescounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    Comment.limit(5).order(created_at: :desc).where(post: self)
  end

  private

  def update_post_counter
    author.increment!(:postscounter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :postscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    Post.limit(3).order(created_at: :desc).where(author: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:id])

    @comment = current_user.comments.new(
      author_id: current_user.id,
      post_id: post.id,
      text: comment_params
    )

    @comment.save if @comment.valid?
    redirect_to user_post_path(current_user, post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:id])

    like = current_user.likes.new(
      author_id: current_user.id,
      post_id: post.id
    )

    if like.save
      redirect_to user_posts_path(current_user, post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(title: post_params[:title], text: post_params[:text], author: current_user)
    if post.save
      redirect_to "/users/#{post.author_id}"
    else
      redirect_to new_user_post_path
    end
  end

  private

  def author_id
    params.require(:user_id)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= bootstrap_form_with model: @comment, url: user_post_comments_url do |f| %>
    <%= f.text_area :text %>
    <%= f.submit "comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="post">
    <img src= "<%= @user.photo %>" /> 
        <%= link_to user_path(@user.id) do %>
             <%= @user.name %>
        <% end %>
    <p>Number of Posts: <%= (@user.posts.count) %></p>
</div>
<% @posts.each do |post| %>
  <%= link_to user_post_path(@user, post) do %>
  <h2>Post: <%= post.id %></h2>
  <% end %>
  <div>
    <p><%= post.text %></p>
    <div>
      <span>Comments: <%= post.commentscounter %></span>
      <span>Likes: <%= post.likescounter %></span>
    </div>
    <div>
   <ul>
    <% post.most_recent_comments.each do |com| %>
     <li>
        <p><%= com.author.name %>: <%= com.text %></p>
     </li>
    <% end %>
    </ul>
    <div>
  </div>
<% end %>

<%= link_to new_user_post_path do  %>
  Add post 
<% end %>

app/views/posts/new.html.erb
<%= bootstrap_form_with model: @post, url: user_posts_url do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :text %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h2>Post #<%= @post.id %> by <%= @post.author.name %></h2>
    <div>
    <p>
        <span class="posts-comment">Comments: <%= @post.commentscounter %></span>
        <span class="posts-likes">Likes: <%= @post.likescounter %></span>
    </p>
    <p><%= @post.text%></p>
    </div>
    <div class="recent-comments">
    <ul>
    <% @post.comments.each do |com| %>
     <li>
        <p><%= com.author.name %>: <%= com.text %></p>
     </li>
    <% end %>
</ul>
<%= link_to new_user_post_comment_path do %>
<button>add comment</button>
<% end %>

<%= bootstrap_form_with url: user_post_likes_url, scope: :like do |f| %>
    <%= f.submit "Like" %>
<% end %>

<%= link_to root_path do %>
    back to all users
<% end %>

app/views/users/index.html.erb
<%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link border-0 bg-light m-3' %>
<ul>
    <% @users.each do |user| %>
     <li>
        <div class="photo">
          <img src= "<%= user.photo %>" /> 
        </div>
          <%= link_to user_path(user.id) do %>
            <p class="text-decoration-none"><%= user.name %></p>
          <% end %>
        <p>Number of Posts: <%= user.postscounter %></p>
     </li>
    <% end %>
</ul>

app/views/users/show.html.erb
<div class="post">
    <img src= "<%= @user.photo %>" /> 
        <%= link_to user_path(@user.id) do %>
             <%= @user.name %>
        <% end %>
    <p>Number of Posts: <%= (@user.posts.count) %></p>
</div>
<div>
    <p><%=@user.bio%></p>
</div>
<ul class="user-post">
    <% @user.most_recent_posts.each do |post| %>
        <li>
         <%= link_to user_post_path(@user, post.id) do %>
            Post #<%= post.id %>
         <% end %>
         <p><%= post.text %></p>
         <p>
            Comments: <%= post.commentscounter %>, Likes: <%= post.likescounter %>
         </p>
        </li>
    <% end %>
</ul>
<%= link_to user_posts_path(@user) do %>
    See all posts
<% end %>